# Generated by Django 6.0 on 2025-12-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.BooleanField(choices=[(True, 'Pendiente'), (False, 'Enviado')], default=True),
        ),
    ]
